package br.edu.ufrb.lasis.humv.view.questionario;

import br.edu.ufrb.lasis.humv.entity.QuestionarioSocioeconomico;
import br.edu.ufrb.lasis.humv.entity.Parente;
import br.edu.ufrb.lasis.humv.entity.Animal;
import br.edu.ufrb.lasis.humv.entity.Documentacao;
import br.edu.ufrb.lasis.humv.utils.InterfaceGraficaUtils;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author tassiovale
 */
public class QuestionarioSocioEconomicoJPanel extends javax.swing.JPanel {
    private double rendaPerCapta = 0, rendaTotal = 0; 
    private List<Parente> parentes;
    /**
     * Creates new form QuestionarioSocioEconomicoJPanel
     */
    public QuestionarioSocioEconomicoJPanel() {
        initComponents();
        this.jRadioButtonSaneamentoSim.setSelected(true);
        this.jRadioButtonEnergiaNao.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSaneamento = new javax.swing.ButtonGroup();
        buttonGroupEnergia = new javax.swing.ButtonGroup();
        buttonGroupEstudante = new javax.swing.ButtonGroup();
        buttonGroupDocumento = new javax.swing.ButtonGroup();
        buttonGroupConsulta = new javax.swing.ButtonGroup();
        buttonGroupExame = new javax.swing.ButtonGroup();
        buttonGroupCirurgia = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelDadosDono = new javax.swing.JPanel();
        jPanelDadosBasicos = new javax.swing.JPanel();
        jButtonPesquisarDono = new javax.swing.JButton();
        jLabelNomeDono = new javax.swing.JLabel();
        jLabelCpfDono = new javax.swing.JLabel();
        jButtonCadastrarNovoDono = new javax.swing.JButton();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jPanelAdicionais = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldIdade = new javax.swing.JFormattedTextField();
        jComboBoxEstadoCivil = new javax.swing.JComboBox<String>();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jTextFieldProfissao = new javax.swing.JTextField();
        jTextFieldOcupacao = new javax.swing.JTextField();
        jPanelMateriais = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButtonSaneamentoSim = new javax.swing.JRadioButton();
        jRadioButtonSaneamentoNao = new javax.swing.JRadioButton();
        jRadioButtonEnergiaSim = new javax.swing.JRadioButton();
        jRadioButtonEnergiaNao = new javax.swing.JRadioButton();
        jFormattedTextFieldRendaFormal = new javax.swing.JFormattedTextField();
        jFormattedTextFieldRendaInformal = new javax.swing.JFormattedTextField();
        jTextFieldTipoConstrucao = new javax.swing.JTextField();
        jTextFieldProgramaRenda = new javax.swing.JTextField();
        jFormattedTextFieldAluguel = new javax.swing.JFormattedTextField();
        jTextFieldCondicaoMoradia = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jRadioButtonEstudanteSim = new javax.swing.JRadioButton();
        jRadioButtonEstudanteNao = new javax.swing.JRadioButton();
        jPanelEstudante = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jFormattedTextFieldGastosMensais = new javax.swing.JFormattedTextField();
        jTextFieldFonteCusteio = new javax.swing.JTextField();
        jTextFieldBeneficio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObservacoes = new javax.swing.JTextArea();
        jPanelDocumentos = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldDocumento = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        dteDataEntrega = new com.toedter.calendar.JDateChooser();
        jButtonDocumentoSalvar = new javax.swing.JButton();
        jButtonDocumentoRemover = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButtonDocumentoDono = new javax.swing.JRadioButton();
        jRadioButtonDocumentoFamilia = new javax.swing.JRadioButton();
        jRadioButtonBolsaFamilia = new javax.swing.JRadioButton();
        jRadioButtonDocumentoOutro = new javax.swing.JRadioButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jCheckBoxNA = new javax.swing.JCheckBox();
        jCheckBoxVistoASocial = new javax.swing.JCheckBox();
        jPanelAnalise = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaVulnerabilidades = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaEncaminhamentos = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextAreaConclusoes = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        Cobranca = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jRadioButtonConsultaNormal = new javax.swing.JRadioButton();
        jRadioButtonConsultaAula = new javax.swing.JRadioButton();
        jRadioButtonConsultaIsencao = new javax.swing.JRadioButton();
        jRadioButtonConsultaDesconto = new javax.swing.JRadioButton();
        jFormattedTextFieldConsulta = new javax.swing.JFormattedTextField();
        jLabel42 = new javax.swing.JLabel();
        jRadioButtonExameNormal = new javax.swing.JRadioButton();
        jRadioButtonExameAula = new javax.swing.JRadioButton();
        jRadioButtonExameIsencao = new javax.swing.JRadioButton();
        jRadioButtonExameDesconto = new javax.swing.JRadioButton();
        jFormattedTextFieldExame = new javax.swing.JFormattedTextField();
        jLabel43 = new javax.swing.JLabel();
        jRadioButtonCirurgiaNormal = new javax.swing.JRadioButton();
        jRadioButtonCirurgiaAula = new javax.swing.JRadioButton();
        jRadioButtonCirurgiaIsencao = new javax.swing.JRadioButton();
        jRadioButtonCirurgiaDesconto = new javax.swing.JRadioButton();
        jFormattedTextFieldCirurgia = new javax.swing.JFormattedTextField();
        jLabel44 = new javax.swing.JLabel();
        jPanelComposicaoFamiliar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFamiliares = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxEscolaridadeFamliar = new javax.swing.JComboBox<String>();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jFormattedIdadeFamilia = new javax.swing.JFormattedTextField();
        jFormattedRendaMembroFamilia = new javax.swing.JFormattedTextField();
        jTextFieldFamiliaNome = new javax.swing.JTextField();
        jTextFieldParentesco = new javax.swing.JTextField();
        jTextFieldFamiliaOcupacao = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jLabelRendaTotal = new javax.swing.JLabel();
        jLabelRendaPerCapta = new javax.swing.JLabel();
        jLabelFamiliaRendaTotal = new javax.swing.JLabel();
        jLabelFamiliaRendaPerCapita = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldFatoresDeclarados = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaBemMaterial = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDividas = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaMotivos = new javax.swing.JTextArea();
        jButtonQuestionarioCancelar = new javax.swing.JButton();
        jButtonQuestionarioSalvar = new javax.swing.JButton();

        jPanelDadosBasicos.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados básicos"));

        jButtonPesquisarDono.setIcon(new javax.swing.ImageIcon("imagens/small_buscar.png"));
        jButtonPesquisarDono.setText("Buscar");
        jButtonPesquisarDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarDonoActionPerformed(evt);
            }
        });

        jLabelNomeDono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNomeDono.setText("Nome:");

        jLabelCpfDono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCpfDono.setText("CPF:");

        jButtonCadastrarNovoDono.setIcon(new javax.swing.ImageIcon("imagens/small_cadastrar.png"));
        jButtonCadastrarNovoDono.setText("Novo");
        jButtonCadastrarNovoDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarNovoDonoActionPerformed(evt);
            }
        });

        jLabelEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEndereco.setText("Endereço:");

        jLabelTelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTelefone.setText("Telefone:");

        javax.swing.GroupLayout jPanelDadosBasicosLayout = new javax.swing.GroupLayout(jPanelDadosBasicos);
        jPanelDadosBasicos.setLayout(jPanelDadosBasicosLayout);
        jPanelDadosBasicosLayout.setHorizontalGroup(
            jPanelDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosBasicosLayout.createSequentialGroup()
                .addComponent(jButtonPesquisarDono, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCadastrarNovoDono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelDadosBasicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeDono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDadosBasicosLayout.createSequentialGroup()
                        .addComponent(jLabelCpfDono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelDadosBasicosLayout.setVerticalGroup(
            jPanelDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosBasicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisarDono)
                    .addComponent(jButtonCadastrarNovoDono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNomeDono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpfDono)
                    .addComponent(jLabelTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEndereco)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelAdicionais.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações adicionais"));

        jLabel1.setText("Idade:");

        jLabel3.setText("Estado civil:");

        jLabel2.setText("Escolaridade:");

        jLabel5.setText("Ocupação:");

        jLabel4.setText("Profissão:");

        jFormattedTextFieldIdade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jComboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado", "Separado", "Divorciado", "Viúvo" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fundamental incompleto", "Fundamental completo", "Médio incompleto", "Médio completo", "Superior incompleto", "Superior completo", "Pós-graduação incompleta", "Pós-graduação completa" }));

        javax.swing.GroupLayout jPanelAdicionaisLayout = new javax.swing.GroupLayout(jPanelAdicionais);
        jPanelAdicionais.setLayout(jPanelAdicionaisLayout);
        jPanelAdicionaisLayout.setHorizontalGroup(
            jPanelAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicionaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdicionaisLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdicionaisLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldProfissao)
                    .addComponent(jTextFieldOcupacao, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAdicionaisLayout.setVerticalGroup(
            jPanelAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicionaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextFieldOcupacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelMateriais.setBorder(javax.swing.BorderFactory.createTitledBorder("Condições materiais"));

        jLabel6.setText("Renda formal (R$):");

        jLabel7.setText("Renda informal (R$):");

        jLabel9.setText("Aluguel/financ. (R$):");

        jLabel8.setText("Condição de moradia:");

        jLabel10.setText("Tipo de construção:");

        jLabel13.setText("Programa transf. renda:");

        jLabel11.setText("Saneamento básico:");

        jLabel12.setText("Energia elétrica:");

        jRadioButtonSaneamentoSim.setText("Sim");
        jRadioButtonSaneamentoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSaneamentoSimActionPerformed(evt);
            }
        });

        jRadioButtonSaneamentoNao.setText("Não");
        jRadioButtonSaneamentoNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSaneamentoNaoActionPerformed(evt);
            }
        });

        jRadioButtonEnergiaSim.setText("Sim");
        jRadioButtonEnergiaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEnergiaSimActionPerformed(evt);
            }
        });

        jRadioButtonEnergiaNao.setText("Não");
        jRadioButtonEnergiaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEnergiaNaoActionPerformed(evt);
            }
        });

        jFormattedTextFieldRendaFormal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        jFormattedTextFieldRendaInformal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        jFormattedTextFieldAluguel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        javax.swing.GroupLayout jPanelMateriaisLayout = new javax.swing.GroupLayout(jPanelMateriais);
        jPanelMateriais.setLayout(jPanelMateriaisLayout);
        jPanelMateriaisLayout.setHorizontalGroup(
            jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMateriaisLayout.createSequentialGroup()
                .addGroup(jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMateriaisLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSaneamentoSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSaneamentoNao))
                    .addGroup(jPanelMateriaisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelMateriaisLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldRendaFormal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMateriaisLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldRendaInformal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMateriaisLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(9, 9, 9)
                                .addComponent(jFormattedTextFieldAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelMateriaisLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel12))
                    .addGroup(jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel13)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMateriaisLayout.createSequentialGroup()
                        .addComponent(jRadioButtonEnergiaSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonEnergiaNao))
                    .addGroup(jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldCondicaoMoradia)
                        .addComponent(jTextFieldProgramaRenda, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                        .addComponent(jTextFieldTipoConstrucao)))
                .addContainerGap())
        );
        jPanelMateriaisLayout.setVerticalGroup(
            jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMateriaisLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldRendaFormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldTipoConstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextFieldCondicaoMoradia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jFormattedTextFieldRendaInformal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldProgramaRenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jFormattedTextFieldAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jRadioButtonSaneamentoSim)
                    .addComponent(jRadioButtonSaneamentoNao)
                    .addComponent(jLabel12)
                    .addComponent(jRadioButtonEnergiaSim)
                    .addComponent(jRadioButtonEnergiaNao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setText("Estudante:");

        jRadioButtonEstudanteSim.setText("Sim");

        jRadioButtonEstudanteNao.setText("Não");

        jPanelEstudante.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel19.setText("Valor dos gastos mensais (R$):");

        jLabel20.setText("Fonte de custeio:");

        jLabel21.setText("Bolsa ou benefício:");

        jLabel22.setText("Observações:");

        jFormattedTextFieldGastosMensais.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        jTextAreaObservacoes.setColumns(20);
        jTextAreaObservacoes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObservacoes);

        javax.swing.GroupLayout jPanelEstudanteLayout = new javax.swing.GroupLayout(jPanelEstudante);
        jPanelEstudante.setLayout(jPanelEstudanteLayout);
        jPanelEstudanteLayout.setHorizontalGroup(
            jPanelEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstudanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEstudanteLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEstudanteLayout.createSequentialGroup()
                        .addGroup(jPanelEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEstudanteLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBeneficio))
                            .addGroup(jPanelEstudanteLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldGastosMensais, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFonteCusteio, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                        .addGap(8, 8, 8))))
        );
        jPanelEstudanteLayout.setVerticalGroup(
            jPanelEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstudanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldGastosMensais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldFonteCusteio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDadosDonoLayout = new javax.swing.GroupLayout(jPanelDadosDono);
        jPanelDadosDono.setLayout(jPanelDadosDonoLayout);
        jPanelDadosDonoLayout.setHorizontalGroup(
            jPanelDadosDonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosDonoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosDonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAdicionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDadosBasicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMateriais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDadosDonoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonEstudanteSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonEstudanteNao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelDadosDonoLayout.setVerticalGroup(
            jPanelDadosDonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosDonoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDadosBasicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosDonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jRadioButtonEstudanteSim)
                    .addComponent(jRadioButtonEstudanteNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Dados do dono", jPanelDadosDono);

        jLabel31.setText("Documento:");

        jLabel32.setText("Data de entrega: ");

        jButtonDocumentoSalvar.setText("Salvar");
        jButtonDocumentoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDocumentoSalvarActionPerformed(evt);
            }
        });

        jButtonDocumentoRemover.setText("Remover");
        jButtonDocumentoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDocumentoRemoverActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Comprovante de endereço");

        jRadioButtonDocumentoDono.setText("Cópia do documento de identidade do dono");
        jRadioButtonDocumentoDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDocumentoDonoActionPerformed(evt);
            }
        });

        jRadioButtonDocumentoFamilia.setText("Cópia do documento de identidade de membro da família");
        jRadioButtonDocumentoFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDocumentoFamiliaActionPerformed(evt);
            }
        });

        jRadioButtonBolsaFamilia.setText("Cópia do cartão Bolsa Família");

        jRadioButtonDocumentoOutro.setText("Outro");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable2);

        jCheckBoxNA.setText("NA");
        jCheckBoxNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNAActionPerformed(evt);
            }
        });

        jCheckBoxVistoASocial.setText("Visto Assistente Social");

        javax.swing.GroupLayout jPanelDocumentosLayout = new javax.swing.GroupLayout(jPanelDocumentos);
        jPanelDocumentos.setLayout(jPanelDocumentosLayout);
        jPanelDocumentosLayout.setHorizontalGroup(
            jPanelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDocumentosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDocumentoRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDocumentoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
            .addGroup(jPanelDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(jPanelDocumentosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonDocumentoDono)
                                .addComponent(jRadioButton1)
                                .addComponent(jRadioButtonDocumentoFamilia)
                                .addComponent(jRadioButtonBolsaFamilia)
                                .addComponent(jRadioButtonDocumentoOutro))
                            .addComponent(jTextFieldDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDocumentosLayout.createSequentialGroup()
                        .addGroup(jPanelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dteDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDocumentosLayout.createSequentialGroup()
                        .addGroup(jPanelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxNA)
                            .addComponent(jCheckBoxVistoASocial))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanelDocumentosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanelDocumentosLayout.setVerticalGroup(
            jPanelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDocumentosLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1))
                    .addGroup(jPanelDocumentosLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(35, 35, 35))
                    .addComponent(dteDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDocumentosLayout.createSequentialGroup()
                        .addComponent(jRadioButtonDocumentoDono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDocumentoFamilia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDocumentosLayout.createSequentialGroup()
                        .addComponent(jCheckBoxNA)
                        .addGap(15, 15, 15)))
                .addGroup(jPanelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonBolsaFamilia)
                    .addComponent(jCheckBoxVistoASocial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonDocumentoOutro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDocumentoRemover)
                    .addComponent(jButtonDocumentoSalvar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Documentos", jPanelDocumentos);

        jLabel33.setText("Breve resumo da história de vida e identificação das vulnerabilidades da família:");

        jTextAreaVulnerabilidades.setColumns(20);
        jTextAreaVulnerabilidades.setRows(5);
        jScrollPane7.setViewportView(jTextAreaVulnerabilidades);

        jLabel34.setText("Orientações e encaminhamentos:");

        jTextAreaEncaminhamentos.setColumns(20);
        jTextAreaEncaminhamentos.setRows(5);
        jScrollPane8.setViewportView(jTextAreaEncaminhamentos);

        jLabel35.setText("Conclusões e outras observações:");

        jTextAreaConclusoes.setColumns(20);
        jTextAreaConclusoes.setRows(5);
        jScrollPane9.setViewportView(jTextAreaConclusoes);

        jLabel36.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel36.setText("Considerar: condições socioeconômicas, histórico de perdas ou interrupção de relações, histórico de violações de direitos,");

        jLabel37.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel37.setText("acesso ao sistema degarantias de direitos, outras situações.");

        javax.swing.GroupLayout jPanelAnaliseLayout = new javax.swing.GroupLayout(jPanelAnalise);
        jPanelAnalise.setLayout(jPanelAnaliseLayout);
        jPanelAnaliseLayout.setHorizontalGroup(
            jPanelAnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnaliseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane9)
                    .addGroup(jPanelAnaliseLayout.createSequentialGroup()
                        .addGroup(jPanelAnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAnaliseLayout.setVerticalGroup(
            jPanelAnaliseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnaliseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Análise", jPanelAnalise);

        jLabel38.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Tipo de cobrança");

        jLabel39.setText("Consultas:");

        jLabel40.setText("Procedimentos ambulatórios/exames:");

        jLabel41.setText("Cirurgia/reprodução:");

        jRadioButtonConsultaNormal.setText("Valor normal");

        jRadioButtonConsultaAula.setText("Valor aula");

        jRadioButtonConsultaIsencao.setText("Isenção");
        jRadioButtonConsultaIsencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonConsultaIsencaoActionPerformed(evt);
            }
        });

        jRadioButtonConsultaDesconto.setText("Desconto");

        jFormattedTextFieldConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel42.setText("%");

        jRadioButtonExameNormal.setText("Valor normal");

        jRadioButtonExameAula.setText("Valor aula");

        jRadioButtonExameIsencao.setText("Isenção");
        jRadioButtonExameIsencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonExameIsencaoActionPerformed(evt);
            }
        });

        jRadioButtonExameDesconto.setText("Desconto");
        jRadioButtonExameDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonExameDescontoActionPerformed(evt);
            }
        });

        jFormattedTextFieldExame.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel43.setText("%");

        jRadioButtonCirurgiaNormal.setText("Valor normal");

        jRadioButtonCirurgiaAula.setText("Valor aula");

        jRadioButtonCirurgiaIsencao.setText("Isenção");
        jRadioButtonCirurgiaIsencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCirurgiaIsencaoActionPerformed(evt);
            }
        });

        jRadioButtonCirurgiaDesconto.setText("Desconto");

        jFormattedTextFieldCirurgia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel44.setText("%");

        javax.swing.GroupLayout CobrancaLayout = new javax.swing.GroupLayout(Cobranca);
        Cobranca.setLayout(CobrancaLayout);
        CobrancaLayout.setHorizontalGroup(
            CobrancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CobrancaLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(CobrancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addGroup(CobrancaLayout.createSequentialGroup()
                        .addComponent(jRadioButtonConsultaNormal)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonConsultaAula)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonConsultaIsencao)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonConsultaDesconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42))
                    .addGroup(CobrancaLayout.createSequentialGroup()
                        .addComponent(jRadioButtonExameNormal)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonExameAula)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonExameIsencao)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonExameDesconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldExame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel43))
                    .addGroup(CobrancaLayout.createSequentialGroup()
                        .addComponent(jRadioButtonCirurgiaNormal)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonCirurgiaAula)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonCirurgiaIsencao)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonCirurgiaDesconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        CobrancaLayout.setVerticalGroup(
            CobrancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CobrancaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel38)
                .addGap(32, 32, 32)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CobrancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonConsultaNormal)
                    .addComponent(jRadioButtonConsultaAula)
                    .addComponent(jRadioButtonConsultaIsencao)
                    .addComponent(jRadioButtonConsultaDesconto)
                    .addComponent(jFormattedTextFieldConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CobrancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonExameNormal)
                    .addComponent(jRadioButtonExameAula)
                    .addComponent(jRadioButtonExameIsencao)
                    .addComponent(jRadioButtonExameDesconto)
                    .addComponent(jFormattedTextFieldExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CobrancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCirurgiaNormal)
                    .addComponent(jRadioButtonCirurgiaAula)
                    .addComponent(jRadioButtonCirurgiaIsencao)
                    .addComponent(jRadioButtonCirurgiaDesconto)
                    .addComponent(jFormattedTextFieldCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addContainerGap(392, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cobrança", Cobranca);

        jTableFamiliares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableFamiliares);

        jLabel14.setText("Nome:");

        jLabel15.setText("Idade:");

        jLabel16.setText("Parentesco:");

        jComboBoxEscolaridadeFamliar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fundamental incompleto", "Fundamental completo", "Médio incompleto", "Médio completo", "Superior incompleto", "Superior completo", "Pós-graduação incompleta", "Pós-graduação completa" }));

        jLabel17.setText("Escolaridade:");

        jLabel23.setText("Ocupação:");

        jLabel24.setText("Renda (R$):");

        jFormattedIdadeFamilia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jFormattedRendaMembroFamilia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        jButtonSalvar.setIcon(new javax.swing.ImageIcon("imagens/small_salvar.png"));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonRemover.setIcon(new javax.swing.ImageIcon("imagens/small_cancelar.png"));
        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jLabelRendaTotal.setText("Renda total (R$):");

        jLabelRendaPerCapta.setText("Renda per capita (R$):");

        jLabelFamiliaRendaTotal.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        jLabelFamiliaRendaPerCapita.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        jLabel27.setText("Fatores de risco social declarados:");

        jLabel28.setText("A família possui algum bem material (casa, carro, etc.)? Qual?");

        jTextAreaBemMaterial.setColumns(20);
        jTextAreaBemMaterial.setRows(5);
        jScrollPane3.setViewportView(jTextAreaBemMaterial);

        jLabel29.setText("A família possui dívidas com banco/empréstimos ou outra situação que comprometa a renda familiar?");

        jTextAreaDividas.setColumns(20);
        jTextAreaDividas.setRows(5);
        jScrollPane4.setViewportView(jTextAreaDividas);

        jLabel30.setText("Quais os principais motivos que impossibilitam custear o tratamento do animal?");

        jTextAreaMotivos.setColumns(20);
        jTextAreaMotivos.setRows(5);
        jScrollPane5.setViewportView(jTextAreaMotivos);

        javax.swing.GroupLayout jPanelComposicaoFamiliarLayout = new javax.swing.GroupLayout(jPanelComposicaoFamiliar);
        jPanelComposicaoFamiliar.setLayout(jPanelComposicaoFamiliarLayout);
        jPanelComposicaoFamiliarLayout.setHorizontalGroup(
            jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComposicaoFamiliarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComposicaoFamiliarLayout.createSequentialGroup()
                        .addGroup(jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanelComposicaoFamiliarLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFamiliaNome)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanelComposicaoFamiliarLayout.createSequentialGroup()
                        .addGroup(jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelComposicaoFamiliarLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFamiliaOcupacao))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelComposicaoFamiliarLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxEscolaridadeFamliar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelComposicaoFamiliarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedIdadeFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedRendaMembroFamilia)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComposicaoFamiliarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanelComposicaoFamiliarLayout.createSequentialGroup()
                        .addGroup(jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelComposicaoFamiliarLayout.createSequentialGroup()
                                .addComponent(jLabelRendaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelFamiliaRendaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelRendaPerCapta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelFamiliaRendaPerCapita, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 125, Short.MAX_VALUE))
                            .addGroup(jPanelComposicaoFamiliarLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFatoresDeclarados)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanelComposicaoFamiliarLayout.createSequentialGroup()
                        .addGroup(jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComposicaoFamiliarLayout.createSequentialGroup()
                        .addGroup(jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3))
                        .addContainerGap())))
        );
        jPanelComposicaoFamiliarLayout.setVerticalGroup(
            jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComposicaoFamiliarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldFamiliaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBoxEscolaridadeFamliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jFormattedIdadeFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jFormattedRendaMembroFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldFamiliaOcupacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemover)
                    .addComponent(jButtonSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRendaTotal)
                        .addComponent(jLabelRendaPerCapta)
                        .addComponent(jLabelFamiliaRendaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelFamiliaRendaPerCapita, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelComposicaoFamiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextFieldFatoresDeclarados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Composição familiar", jPanelComposicaoFamiliar);

        jButtonQuestionarioCancelar.setIcon(new javax.swing.ImageIcon("imagens/small_cancelar.png"));
        jButtonQuestionarioCancelar.setText("Cancelar");
        jButtonQuestionarioCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuestionarioCancelarActionPerformed(evt);
            }
        });

        jButtonQuestionarioSalvar.setIcon(new javax.swing.ImageIcon("imagens/small_salvar.png"));
        jButtonQuestionarioSalvar.setText("Salvar");
        jButtonQuestionarioSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuestionarioSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonQuestionarioCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonQuestionarioSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQuestionarioSalvar)
                    .addComponent(jButtonQuestionarioCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarDonoActionPerformed
        /*JFrame jFrame = new JFrame("Busca");
        PropriedadesBuscaDono propriedadesBusca = new PropriedadesBuscaDono(PropriedadesBusca.OPCAO_SELECIONAR, jFrame, this);
        BuscaJPanel buscaPanel = new BuscaJPanel("BUSCA DE DONO", propriedadesBusca);
        jFrame.setContentPane(buscaPanel);
        InterfaceGraficaUtils.exibirJanela(jFrame);*/
    }//GEN-LAST:event_jButtonPesquisarDonoActionPerformed

    private void jButtonCadastrarNovoDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarNovoDonoActionPerformed
        //new CadastrarDonoJDialog(this).setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarNovoDonoActionPerformed

    private void jRadioButtonSaneamentoNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSaneamentoNaoActionPerformed
        // TODO add your handling code here:
        this.jRadioButtonSaneamentoSim.setSelected(false);
    }//GEN-LAST:event_jRadioButtonSaneamentoNaoActionPerformed

    private void jRadioButtonEnergiaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEnergiaNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEnergiaNaoActionPerformed

    private void jButtonDocumentoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDocumentoSalvarActionPerformed
        
    }//GEN-LAST:event_jButtonDocumentoSalvarActionPerformed

    private void jButtonDocumentoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDocumentoRemoverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDocumentoRemoverActionPerformed

    private void jRadioButtonDocumentoDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDocumentoDonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDocumentoDonoActionPerformed

    private void jRadioButtonDocumentoFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDocumentoFamiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDocumentoFamiliaActionPerformed

    private void jCheckBoxNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxNAActionPerformed

    private void jRadioButtonConsultaIsencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonConsultaIsencaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonConsultaIsencaoActionPerformed

    private void jRadioButtonExameIsencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonExameIsencaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonExameIsencaoActionPerformed

    private void jRadioButtonCirurgiaIsencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCirurgiaIsencaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCirurgiaIsencaoActionPerformed

    private void jRadioButtonExameDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonExameDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonExameDescontoActionPerformed

    private void jButtonQuestionarioCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuestionarioCancelarActionPerformed
        
    }//GEN-LAST:event_jButtonQuestionarioCancelarActionPerformed

    private void jButtonQuestionarioSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuestionarioSalvarActionPerformed
        
    }//GEN-LAST:event_jButtonQuestionarioSalvarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed

    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Parente parente = new Parente();

        if (this.jTextFieldFamiliaNome.getText().isEmpty()) {
            InterfaceGraficaUtils.validaCampoVazio("Nome do familiar");
            return;
        }
        String nome = this.jTextFieldFamiliaNome.getText();
        parente.setNome(nome);

        if (this.jFormattedIdadeFamilia.getText().isEmpty()) {
            InterfaceGraficaUtils.validaCampoVazio("Idade do familiar");
            return;
        }
        int idade = Integer.parseInt(this.jFormattedIdadeFamilia.getText());
        parente.setIdade(idade);

        if (this.jTextFieldParentesco.getText().isEmpty()) {
            InterfaceGraficaUtils.validaCampoVazio("Parentesco do familiar");
            return;
        }
        String parentesco = this.jTextFieldParentesco.getText();
        parente.setParentesco(parentesco);

        int escolaridade = this.jComboBoxEscolaridadeFamliar.getSelectedIndex();
        parente.setEscolaridade(escolaridade);

        if (this.jTextFieldFamiliaOcupacao.getText().isEmpty()) {
            InterfaceGraficaUtils.validaCampoVazio("Ocupação do familiar");
            return;
        }
        String ocupacao = this.jTextFieldFamiliaOcupacao.getText();
        parente.setOcupacao(ocupacao);

        if (this.jFormattedRendaMembroFamilia.getText().isEmpty()) {
            InterfaceGraficaUtils.validaCampoVazio("Renda do familiar");
            return;
        }
        double renda = Double.parseDouble(this.jFormattedRendaMembroFamilia.getText());
        parente.setRenda(renda);

        parentes.add(parente);
        limparTextfieldsInfoFamiliar();
        atualizaTabelaFamiliares();
        atualizaCalculoRenda();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jRadioButtonSaneamentoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSaneamentoSimActionPerformed
        // TODO add your handling code here:
        this.jRadioButtonSaneamentoNao.setSelected(false);
    }//GEN-LAST:event_jRadioButtonSaneamentoSimActionPerformed

    private void jRadioButtonEnergiaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEnergiaSimActionPerformed
        // TODO add your handling code here:
        this.jRadioButtonEnergiaNao.setSelected(false);
    }//GEN-LAST:event_jRadioButtonEnergiaSimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cobranca;
    private javax.swing.ButtonGroup buttonGroupCirurgia;
    private javax.swing.ButtonGroup buttonGroupConsulta;
    private javax.swing.ButtonGroup buttonGroupDocumento;
    private javax.swing.ButtonGroup buttonGroupEnergia;
    private javax.swing.ButtonGroup buttonGroupEstudante;
    private javax.swing.ButtonGroup buttonGroupExame;
    private javax.swing.ButtonGroup buttonGroupSaneamento;
    private com.toedter.calendar.JDateChooser dteDataEntrega;
    private javax.swing.JButton jButtonCadastrarNovoDono;
    private javax.swing.JButton jButtonDocumentoRemover;
    private javax.swing.JButton jButtonDocumentoSalvar;
    private javax.swing.JButton jButtonPesquisarDono;
    private javax.swing.JButton jButtonQuestionarioCancelar;
    private javax.swing.JButton jButtonQuestionarioSalvar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBoxNA;
    private javax.swing.JCheckBox jCheckBoxVistoASocial;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxEscolaridadeFamliar;
    private javax.swing.JComboBox<String> jComboBoxEstadoCivil;
    private javax.swing.JFormattedTextField jFormattedIdadeFamilia;
    private javax.swing.JFormattedTextField jFormattedRendaMembroFamilia;
    private javax.swing.JFormattedTextField jFormattedTextFieldAluguel;
    private javax.swing.JFormattedTextField jFormattedTextFieldCirurgia;
    private javax.swing.JFormattedTextField jFormattedTextFieldConsulta;
    private javax.swing.JFormattedTextField jFormattedTextFieldExame;
    private javax.swing.JFormattedTextField jFormattedTextFieldGastosMensais;
    private javax.swing.JFormattedTextField jFormattedTextFieldIdade;
    private javax.swing.JFormattedTextField jFormattedTextFieldRendaFormal;
    private javax.swing.JFormattedTextField jFormattedTextFieldRendaInformal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCpfDono;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelFamiliaRendaPerCapita;
    private javax.swing.JLabel jLabelFamiliaRendaTotal;
    private javax.swing.JLabel jLabelNomeDono;
    private javax.swing.JLabel jLabelRendaPerCapta;
    private javax.swing.JLabel jLabelRendaTotal;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPanelAdicionais;
    private javax.swing.JPanel jPanelAnalise;
    private javax.swing.JPanel jPanelComposicaoFamiliar;
    private javax.swing.JPanel jPanelDadosBasicos;
    private javax.swing.JPanel jPanelDadosDono;
    private javax.swing.JPanel jPanelDocumentos;
    private javax.swing.JPanel jPanelEstudante;
    private javax.swing.JPanel jPanelMateriais;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonBolsaFamilia;
    private javax.swing.JRadioButton jRadioButtonCirurgiaAula;
    private javax.swing.JRadioButton jRadioButtonCirurgiaDesconto;
    private javax.swing.JRadioButton jRadioButtonCirurgiaIsencao;
    private javax.swing.JRadioButton jRadioButtonCirurgiaNormal;
    private javax.swing.JRadioButton jRadioButtonConsultaAula;
    private javax.swing.JRadioButton jRadioButtonConsultaDesconto;
    private javax.swing.JRadioButton jRadioButtonConsultaIsencao;
    private javax.swing.JRadioButton jRadioButtonConsultaNormal;
    private javax.swing.JRadioButton jRadioButtonDocumentoDono;
    private javax.swing.JRadioButton jRadioButtonDocumentoFamilia;
    private javax.swing.JRadioButton jRadioButtonDocumentoOutro;
    private javax.swing.JRadioButton jRadioButtonEnergiaNao;
    private javax.swing.JRadioButton jRadioButtonEnergiaSim;
    private javax.swing.JRadioButton jRadioButtonEstudanteNao;
    private javax.swing.JRadioButton jRadioButtonEstudanteSim;
    private javax.swing.JRadioButton jRadioButtonExameAula;
    private javax.swing.JRadioButton jRadioButtonExameDesconto;
    private javax.swing.JRadioButton jRadioButtonExameIsencao;
    private javax.swing.JRadioButton jRadioButtonExameNormal;
    private javax.swing.JRadioButton jRadioButtonSaneamentoNao;
    private javax.swing.JRadioButton jRadioButtonSaneamentoSim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableFamiliares;
    private javax.swing.JTextArea jTextAreaBemMaterial;
    private javax.swing.JTextArea jTextAreaConclusoes;
    private javax.swing.JTextArea jTextAreaDividas;
    private javax.swing.JTextArea jTextAreaEncaminhamentos;
    private javax.swing.JTextArea jTextAreaMotivos;
    private javax.swing.JTextArea jTextAreaObservacoes;
    private javax.swing.JTextArea jTextAreaVulnerabilidades;
    private javax.swing.JTextField jTextFieldBeneficio;
    private javax.swing.JTextField jTextFieldCondicaoMoradia;
    private javax.swing.JTextField jTextFieldDocumento;
    private javax.swing.JTextField jTextFieldFamiliaNome;
    private javax.swing.JTextField jTextFieldFamiliaOcupacao;
    private javax.swing.JTextField jTextFieldFatoresDeclarados;
    private javax.swing.JTextField jTextFieldFonteCusteio;
    private javax.swing.JTextField jTextFieldOcupacao;
    private javax.swing.JTextField jTextFieldParentesco;
    private javax.swing.JTextField jTextFieldProfissao;
    private javax.swing.JTextField jTextFieldProgramaRenda;
    private javax.swing.JTextField jTextFieldTipoConstrucao;
    // End of variables declaration//GEN-END:variables

    private void limparTextfieldsInfoFamiliar() {
        this.jTextFieldFamiliaNome.setText(null);
        this.jFormattedIdadeFamilia.setText(null);
        this.jTextFieldParentesco.setText(null);
        this.jTextFieldFamiliaOcupacao.setText(null);
        this.jFormattedRendaMembroFamilia.setText(null); //To change body of generated methods, choose Tools | Templates.
    }

    private void atualizaTabelaFamiliares() {
        String colunas[] ={"Nome","Parentesco","Renda R$"}; 
        DefaultTableModel model = new DefaultTableModel(colunas, 0);
        
        parentes.forEach((p) -> {
            model.addRow(new String[]{p.getNome(),p.getParentesco(),""+p.getRenda()});
        });
        jTableFamiliares.setModel(model); //To change body of generated methods, choose Tools | Templates.
    }

    private void atualizaCalculoRenda() {
        int qtdParentes=0;
        for(Parente parente:parentes){
            rendaTotal += parente.getRenda();
            ++qtdParentes;
        }
        rendaPerCapta = rendaTotal/qtdParentes;
        jLabelRendaTotal.setText("Renda total (R$): "+rendaTotal);
        jLabelRendaPerCapta.setText("Renda per capta (R$): "+rendaTotal); //To change body of generated methods, choose Tools | Templates.
    }
}
