/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufrb.lasis.humv.view.agendamento;

import br.edu.ufrb.lasis.humv.HUMVApp;
import br.edu.ufrb.lasis.humv.entity.Atendimento;
import br.edu.ufrb.lasis.humv.entity.Usuario;
import br.edu.ufrb.lasis.humv.rest.RESTConnectionException;
import br.edu.ufrb.lasis.humv.rest.RESTMethods;
import br.edu.ufrb.lasis.humv.utils.InterfaceGraficaUtils;
import br.edu.ufrb.lasis.humv.utils.ValidationsUtils;
import com.sun.jersey.api.client.ClientResponse;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.codehaus.jackson.type.TypeReference;

/**
 *
 * @author tassiovale
 */
public class BuscarAgendaMedicoJPanel extends javax.swing.JPanel {

    private List<Usuario> medicos = null;

    /**
     * Creates new form RealizarAgendamentoJPanel
     */
    public BuscarAgendaMedicoJPanel() {
        initComponents();
        customInitComponents();
    }

    private void customInitComponents() {
        List<Usuario> listMedicos = getMedicos();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Usuario usuario : listMedicos) {
            MedicoComboBox medico = new MedicoComboBox(usuario);
            model.addElement(medico);
        }
        comboBoxMedicos.setModel(model);
    }

    private List<Usuario> getMedicos() {
        if (medicos == null) {
            try {
                ClientResponse response = RESTMethods.get("/api/usuario/obterMedicosAtivos");
                medicos = (List<Usuario>) RESTMethods.getObjectFromJSON(response, new TypeReference<List<Usuario>>() {
                });
            } catch (RESTConnectionException | IOException ex) {
                InterfaceGraficaUtils.erroConexao();
            }
        }
        return medicos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxMedicos = new javax.swing.JComboBox<>();
        jDateChooserDiaAgenda = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButtonCarregar = new javax.swing.JButton();
        jScrollPaneTabela = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("AGENDAMENTO");

        jLabel1.setText("Médico:");

        comboBoxMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMedicosActionPerformed(evt);
            }
        });

        jLabel2.setText("Data:");

        jButtonCarregar.setText("Carregar");
        jButtonCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarregarActionPerformed(evt);
            }
        });

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPaneTabela)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserDiaAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButton1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(comboBoxMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserDiaAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCarregar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarregarActionPerformed
        if (getMedicos() == null || getMedicos().isEmpty()) {
            InterfaceGraficaUtils.erroResposta("Não existem médicos para consulta. Por favor, realize o cadastro do médico.");
        } else if (jDateChooserDiaAgenda.getDate() == null) {
            InterfaceGraficaUtils.erroResposta("Por favor, informe a data para carregar a agenda do médico " + (MedicoComboBox) comboBoxMedicos.getSelectedItem() + ".");
            jDateChooserDiaAgenda.setFocusable(true);
        } else {
            try {
                String dataStr = ValidationsUtils.obterDataString(jDateChooserDiaAgenda.getDate());
                String emailMedico = ((MedicoComboBox) comboBoxMedicos.getSelectedItem()).getUsuario().getEmail();
                ClientResponse response = RESTMethods.get("/api/atendimento/searchByDateAndMedicoSemCancelados?data=" + dataStr + "&idEmailMedico=" + emailMedico);
                List<Atendimento> atendimentos = (List<Atendimento>) RESTMethods.getObjectFromJSON(response, new TypeReference<List<Atendimento>>() {
                });

                AgendaJPanel agendaJPanel = new AgendaJPanel(atendimentos, jDateChooserDiaAgenda.getDate());
                jScrollPaneTabela.setViewportView(agendaJPanel);
                jScrollPaneTabela.revalidate();
            } catch (RESTConnectionException | IOException ex) {
                InterfaceGraficaUtils.erroConexao();
            }
        }
    }//GEN-LAST:event_jButtonCarregarActionPerformed

    private void comboBoxMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMedicosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean sair = InterfaceGraficaUtils.dialogoSair();
        if (sair) {
            HUMVApp.setPainelCentralComLogo();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxMedicos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCarregar;
    private com.toedter.calendar.JDateChooser jDateChooserDiaAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPaneTabela;
    // End of variables declaration//GEN-END:variables
}

class MedicoComboBox {

    private Usuario usuario;

    public MedicoComboBox(Usuario usuario) {
        this.usuario = usuario;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    @Override
    public String toString() {
        return usuario.getNome();
    }

}
