package br.edu.ufrb.lasis.humv.view.procedimento;

import br.edu.ufrb.lasis.humv.HUMVApp;
import br.edu.ufrb.lasis.humv.utils.MessagesUtils;
import br.edu.ufrb.lasis.humv.entity.Procedimento;
import br.edu.ufrb.lasis.humv.entity.Setor;
import br.edu.ufrb.lasis.humv.rest.RESTConnectionException;
import br.edu.ufrb.lasis.humv.rest.RESTMethods;
import br.edu.ufrb.lasis.humv.view.setor.CadastroSetorJDialog;
import com.sun.jersey.api.client.ClientResponse;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Luiz
 */
public class CadastrarProcedimentoJPanel extends javax.swing.JPanel implements ActionListener {
    JFrame parent;
    String codSetor;
    String nomeProcedimento;
    String codProcedimento;
    String valorProcedimento;
    String nomeSetor;
    final private String servicoSetor = "/api/setor";
    final private String servicoProcedimento = "/api/procedimento";
    private static final Logger LOG = Logger.getLogger(CadastrarProcedimentoJPanel.class.getName());
    private Procedimento procedimentoSelecionado;

    /**
     * Creates new form CadastroProcedimento
     */
    public CadastrarProcedimentoJPanel() {
        initComponents();
        customInitComponents();
    }

    public CadastrarProcedimentoJPanel(Procedimento procedimentoSelecionado) {
        this.procedimentoSelecionado = procedimentoSelecionado;
        initComponents();
        customInitComponents();
    }

    private void customInitComponents() {
        jButtonConfirmar.addActionListener(this);
        jButtonCancelar.addActionListener(this);
        jTextFieldNome.setFocusable(true);

        if (procedimentoSelecionado != null) {
            jLabelTitulo.setText("ALTERAÇÃO DO PROCEDIMENTO");
            jTextFieldNome.setText(procedimentoSelecionado.getNome());
            jTextFieldCodigo.setText(procedimentoSelecionado.getCodigo());
            jTextFieldPreco.setText(""+procedimentoSelecionado.getValor());
            ClientResponse response = null;
            try {
                response = RESTMethods.get(servicoSetor + "/" + procedimentoSelecionado.getCodSetor());
                Setor at = response.getEntity(Setor.class);
                jLabelNomeSetor.setText("Nome: " + at.getNome());
                codSetor = at.getCodigo();
                jLabelSetorCodigo.setText("Código: "+ codSetor);
            } catch (RESTConnectionException ex) {
                Logger.getLogger(CadastrarProcedimentoJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInformacoesSetor = new javax.swing.JPanel();
        jButtonCadastrarSetor = new javax.swing.JButton();
        jButtonPesqusar = new javax.swing.JButton();
        jTextFieldCodSetor = new javax.swing.JTextField();
        jLabelCodSetorBusca = new javax.swing.JLabel();
        jLabelNomeSetor = new javax.swing.JLabel();
        jLabelSetorCodigo = new javax.swing.JLabel();
        jPanelInformacoesProcedimento = new javax.swing.JPanel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldPreco = new javax.swing.JTextField();
        jLabelPreco = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        jPanelInformacoesSetor.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do setor"));

        jButtonCadastrarSetor.setText("Cadastrar novo...");
        jButtonCadastrarSetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadastrarSetorMouseClicked(evt);
            }
        });

        jButtonPesqusar.setText("Pesquisar");
        jButtonPesqusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesqusarActionPerformed(evt);
            }
        });

        jLabelCodSetorBusca.setText("Informe o código do setor");

        jLabelNomeSetor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNomeSetor.setText("Nome: ");

        jLabelSetorCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSetorCodigo.setText("Código: ");

        javax.swing.GroupLayout jPanelInformacoesSetorLayout = new javax.swing.GroupLayout(jPanelInformacoesSetor);
        jPanelInformacoesSetor.setLayout(jPanelInformacoesSetorLayout);
        jPanelInformacoesSetorLayout.setHorizontalGroup(
            jPanelInformacoesSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacoesSetorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformacoesSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformacoesSetorLayout.createSequentialGroup()
                        .addComponent(jTextFieldCodSetor)
                        .addGap(10, 10, 10))
                    .addGroup(jPanelInformacoesSetorLayout.createSequentialGroup()
                        .addGroup(jPanelInformacoesSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodSetorBusca)
                            .addComponent(jLabelNomeSetor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelInformacoesSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformacoesSetorLayout.createSequentialGroup()
                        .addComponent(jButtonPesqusar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadastrarSetor))
                    .addComponent(jLabelSetorCodigo))
                .addContainerGap())
        );
        jPanelInformacoesSetorLayout.setVerticalGroup(
            jPanelInformacoesSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacoesSetorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCodSetorBusca)
                .addGap(7, 7, 7)
                .addGroup(jPanelInformacoesSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesqusar)
                    .addComponent(jButtonCadastrarSetor)
                    .addComponent(jTextFieldCodSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanelInformacoesSetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeSetor)
                    .addComponent(jLabelSetorCodigo))
                .addContainerGap())
        );

        jPanelInformacoesProcedimento.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do procedimento"));

        jLabelNome.setText("Nome:");

        jLabelCodigo.setText("Código:");

        jLabelPreco.setText("Preço R$:");

        javax.swing.GroupLayout jPanelInformacoesProcedimentoLayout = new javax.swing.GroupLayout(jPanelInformacoesProcedimento);
        jPanelInformacoesProcedimento.setLayout(jPanelInformacoesProcedimentoLayout);
        jPanelInformacoesProcedimentoLayout.setHorizontalGroup(
            jPanelInformacoesProcedimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacoesProcedimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformacoesProcedimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformacoesProcedimentoLayout.createSequentialGroup()
                        .addGroup(jPanelInformacoesProcedimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNome)
                            .addGroup(jPanelInformacoesProcedimentoLayout.createSequentialGroup()
                                .addGroup(jPanelInformacoesProcedimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNome)
                                    .addComponent(jLabelCodigo)
                                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformacoesProcedimentoLayout.createSequentialGroup()
                        .addGap(0, 178, Short.MAX_VALUE)
                        .addGroup(jPanelInformacoesProcedimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPreco))
                        .addGap(157, 157, 157))))
        );
        jPanelInformacoesProcedimentoLayout.setVerticalGroup(
            jPanelInformacoesProcedimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacoesProcedimentoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInformacoesProcedimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jLabelPreco))
                .addGap(10, 10, 10)
                .addGroup(jPanelInformacoesProcedimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitulo.setText("CADASTRAMENTO DE PROCEDIMENTO");

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelInformacoesProcedimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInformacoesSetor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConfirmar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanelInformacoesSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelInformacoesProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonConfirmar))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarSetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrarSetorMouseClicked
        // TODO add your handling code here:
        CadastroSetorJDialog setor = new CadastroSetorJDialog(parent, true, this);
        setor.setTitle("CADASTRAMENTO DE SETOR");
        setor.setLocationRelativeTo(null);
        setor.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarSetorMouseClicked
    
    public void setCodSetorNull() {
        this.codSetor=" ";
        this.nomeSetor = null;
        this.jLabelNomeSetor.setText("Nome: ");
        this.jLabelCodSetorBusca.setText("Código: ");
    }
    public void setCodSetor(String nome,String cod) {
        this.codSetor=cod;
        if(!cod.equals(" ")){
            this.nomeSetor = nome;
            this.jLabelNomeSetor.setText("Nome: "+nome);
            this.jLabelSetorCodigo.setText("Código: "+cod);
        }
    }
    private void jButtonPesqusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesqusarActionPerformed
        ClientResponse response;
        if (!jTextFieldCodSetor.getText().isEmpty()) {
            try {
                response = RESTMethods.get(servicoSetor + "/" + this.jTextFieldCodSetor.getText() + "");
                Setor at = response.getEntity(Setor.class);
                nomeSetor = at.getNome();
                codSetor = at.getCodigo();
                this.jLabelNomeSetor.setText("Nome: " + nomeSetor);
                this.jLabelSetorCodigo.setText("Código: "+codSetor);
            } catch (RESTConnectionException ex) {
                Logger.getLogger(CadastrarProcedimentoJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            MessagesUtils.validaCampoVazio("de busca");
        }
    }//GEN-LAST:event_jButtonPesqusarActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        if (nomeSetor == null) {
            MessagesUtils.validaCampoVazio("setor");
            return;
        }
        char sexo;
        float peso;
        int idade;
        boolean pequenoPort;
        if (this.jTextFieldNome.getText().isEmpty()) {
            MessagesUtils.validaCampoVazio("nome");
            return;
        }
        String nome = this.jTextFieldNome.getText();
        if (this.jTextFieldCodigo.getText().isEmpty()) {
            MessagesUtils.validaCampoVazio("código");
            return;
        }
        String codigo = this.jTextFieldCodigo.getText();
        if (jTextFieldPreco.getText().isEmpty()) {
            MessagesUtils.validaCampoVazio("preço");
            return;
        }
        double valor = Double.parseDouble(this.jTextFieldPreco.getText());
        
        Procedimento procedimento = new Procedimento();
        procedimento.setValor(valor);
        procedimento.setCodigo(codigo);
        procedimento.setNome(nome);
        procedimento.setCodSetor(codSetor);
        try {
            ClientResponse response; 
            if(procedimentoSelecionado == null){
                response = RESTMethods.post(this.servicoProcedimento, procedimento);
            }
            else{
                response = RESTMethods.put(this.servicoProcedimento, procedimento);
            }
            String resposta = response.getEntity(String.class);
            if (!resposta.equalsIgnoreCase("ok")) {
                if(procedimentoSelecionado==null)
                    MessagesUtils.erroCadastro("procedimento");
                else
                    MessagesUtils.erroAtualizacao("procedimento");
            }else{
                if(procedimentoSelecionado==null)
                    MessagesUtils.sucessoCadastro("procedimento");
                else
                    MessagesUtils.sucessoAtualizacao("procedimento");
                HUMVApp.exibirMensagemCarregamento();
                HUMVApp.setPainelCentralComLogo();
                HUMVApp.esconderMensagemCarregamento();
            }
        } catch (RESTConnectionException ex) {
            Logger.getLogger(CadastrarProcedimentoJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int op = MessagesUtils.dialogoCancelar("o cadastro", "procedimento");
        if(op == JOptionPane.OK_OPTION){
            this.setVisible(false);
            System.gc();
            HUMVApp.exibirMensagemCarregamento();
            HUMVApp.setPainelCentralComLogo();
            HUMVApp.esconderMensagemCarregamento();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarSetor;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonPesqusar;
    private javax.swing.JLabel jLabelCodSetorBusca;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeSetor;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelSetorCodigo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelInformacoesProcedimento;
    private javax.swing.JPanel jPanelInformacoesSetor;
    private javax.swing.JTextField jTextFieldCodSetor;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPreco;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {}
}
